modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
[[mods]]
modId = "terra_guns"
version = "0.0.1"
displayName = "TerraGuns"
authors = "xiaohunao, Kaleb Langley"

description = ''''''

[[mixins]]
config="terra_guns.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"


[[dependencies.terra_guns]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.terra_guns]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"